### ISSUE TITLE
How can i start the schedule earlier than 9AM?

### ISSUE THREAD

**Issue by vickyintokyo** [Rogger794/react-appointment-picker#7]
Hi Roger,
Thanks for the component. It really fits the bill for my app.
Below is not an issue but more of requests.
1. Is it possible to pass the start time of the schedule via parameter? not always starting at 9
2. Is it possible to have prev and next button, with which user can view data for next week or prev week?

Thanks much 
Vikram

**Comment by Rogger794** [comment]
Hi @vickyintokyo:
1. For setting a different starter time, you should pass an initialDay with a date with time, example: initialDay={new Date("Fri May 04 2018 17:00:00 GMT-0500")}

**Comment by vickyintokyo** [comment]
@Rogger794  Perfect. Thank you so much quick turnaround. 
1. Understood. This was easy.
2. I see, thats what my first thought. So I think i need to right extra code to handle the user actions on Prev and Next button. Let me work on it. let me know if you have time and planning to handle it as extension to your component. 
Again thanks much for the component. 
Stay safe !!

**Comment by Rogger794** [comment]
Also I used to use this component, this one could work with react-appointment-picker together https://ant.design/components/pagination/

**Comment by vickyintokyo** [comment]
@Rogger794  Thank you so much. Let me close this issue.
